name: Comment

on:
  workflow_run:
    workflows: [Upload]
    types:
      - completed

jobs:
  comment:
    if: ${{ github.repository_owner == 'dgeni' }}
    runs-on: ubuntu-latest
    name: Add comment to the artifact upload id
    steps:
      - name: print
        run: echo ${{ github.event.workflow_run.pull_requests[0].id }}
      - name: Comment on PR with Link
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          number: ${{ github.event.workflow_run.pull_requests[0].id }}
          message: |
            ${{ github.event.workflow_run.id }}
