name: Comment

on:
  workflow_run:
    workflows: [Upload]
    types:
      - completed

jobs:
  comment:
    if: ${{ github.repository_owner == 'dgeni' }}
    name: Add comment to the artifact upload id
    steps:
      - name: Comment on PR with Link
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            ${{ github.event.workflow_run.id }}
