name: Comment

on:
  workflow_run:
    workflows: [Upload]
    types:
      - completed

jobs:
  comment:
    if: ${{ github.repository_owner == 'dgeni' }}
    runs-on: ubuntu-latest
    name: Add comment to the artifact upload id
    steps:
      - name: "Download pr_number artifact"
        uses: actions/github-script@v5
        with:
          script: |
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.payload.workflow_run.id,
            });
            let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "pr_number"
            })[0];
            let download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            let fs = require('fs');
            fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/pr_number.zip`, Buffer.from(download.data));

      - name: "Unzip pr_number artifact"
        run: unzip pr_number.zip
      - name: "Write PR number to environment"
        uses: actions/github-script@v5
        with:
          script: |
            let fs = require('fs');
            let pr_number = Number(fs.readFileSync('./pr_number'));
            fs.appendFileSync(process.env.GITHUB_ENV, `WORKFLOW_RUN_PR=${pr_number}`);

      - name: "Comment on PR"
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          number: ${{ env.WORKFLOW_RUN_PR }}
          message: |
            Commenting on ${{ env.WORKFLOW_RUN_PR }}
