name: Upload

on: pull_request

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: node -e "require('fs').writeFileSync(`pr-{{github.event.number}}.txt`, {{ github.event.number }}, 'utf8')"
      - name: Upload package as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: pr
          path: pr*.txt
