name: Upload

on: pull_request

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Upload package as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: foo
          path: README
